name: Deploy Dev to GitHub Pages

on:
  push:
    branches:
      - dev   # or 'dev' if you want to deploy from that branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./       
          force_orphan: true    
          user_name: 'github-actions'
          user_email: 'github-actions@github.com'
